{
    'name': 'TPV Pedidos',
    'version': '19.0.3.0.0',
    'category': 'Sales/Point of Sale',
    'summary': 'Pedidos desde tiendas al obrador con diferenciación de encargos y pedidos de tienda',
    'author': 'Pablo García Fernández',
    'website': 'https://github.com/pablogarciapda',
    'license': 'LGPL-3',
    'depends': [
        'point_of_sale',
        'sale',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/security_rules.xml',
        'data/sequence_data.xml',
        'data/res_partner_data.xml',
        'data/tpv_nota_categoria_data.xml',
        'data/cron_data.xml',
        'data/initial_config_data.xml',
        'views/tpv_nota_categoria_views.xml',
        'views/tpv_pedido_views.xml',
        'views/tpv_pedido_config_views.xml',
        'views/pos_category_views.xml',
        'views/menu_views.xml',
        'views/web_informes_templates.xml',
        'report/report_pedido_obrador.xml',
    ],
    'assets': {
        'point_of_sale._assets_pos': [
            'tpv_pedidos/static/src/js/login_screen_patch.js',
            'tpv_pedidos/static/src/js/pedido_screen.js',
            'tpv_pedidos/static/src/xml/login_screen_patch.xml',
            'tpv_pedidos/static/src/xml/pedido_screen.xml',
            'tpv_pedidos/static/src/xml/nota_linea_popup.xml',
            'tpv_pedidos/static/src/xml/pedido_confirm_popup.xml',
            'tpv_pedidos/static/src/scss/pedido_screen.scss',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}