from . import tpv_nota_categoria
from . import tpv_pedido
from . import tpv_pedido_linea
from . import tpv_pedido_config
from . import sale_order_inherit
from . import res_partner_inherit
from . import pos_category_inherit
from . import tpv_pedido_report_line
from . import tpv_backup_file